### ISSUE TITLE
https请求返回的数据读取乱码

### ISSUE THREAD

**Issue by zfgx** [clearthesky/byproxy#1]
https请求返回的数据读取乱码,看了下编码是Content-Encoding: deflate，这个可以解决吗

**Comment by clearthesky** [comment]
看了下代码，对deflate压缩处理的那块是写错了。
你能保存一下有问题数据贴上来吗？我测试一下，一时间还真找不到deflate压缩的站点。

**Comment by clearthesky** [comment]
提交了新版本0.5.1，解决了deflate的问题

**Comment by zfgx** [comment]
太棒了，可以显示了，就是你新提交的代码报错了

**Comment by zfgx** [comment]
我想把你这项目弄成一个库，但是能力有限，看了好久啊

**Comment by zfgx** [comment]
请求编码Accept-Encoding: gzip的请求数据也乱码，返回的数据也是gzip不乱码,
POST http://59.37.96.170:8080/?tk=b6399af2254113971e6d8fa2c4cbaed3fed390e5157441c78becf1fa3fb60bb9323f6e7f03b881db21133b1bf2ae5bc5&iv=95aa75a6f989b38c&encrypt=17 HTTP/1.1
Q-UA2: QV=3&PL=ADR&PR=WX&PP=com.tencent.mm&PPVN=6.5.7&TBSVC=43101&CO=BK&COVC=043220&PB=GE&VE=GA&DE=PHONE&CHID=0&LCID=9422&MO= PRO5 &RL=1080*1920&OS=5.1&API=22
Accept: */*
User-Agent: Mozilla/5.0 (Linux; U; Android 5.1; zh-cn; ) AppleWebKit/533.1 (KHTML, like Gecko) Mobile Safari/533.1
Connection: Close
Q-GUID: 9E4A0DA58C8BF9D2C6FC06214CAA328A7991585014C135165C427CDE2C33E103
Accept-Encoding: gzip
Content-Type: application/x-www-form-urlencoded
Content-Length: 1008
Host: 59.37.96.170:8080

**Comment by clearthesky** [comment]
把UI那部分去掉基本就是个库了。

Accept-Encoding: gzip，这个是表示可以接受的响应的编码，不是请求本身的编码，http标准里面请求是不能做gzip压缩的，所以看到请求乱码和gzip应该无关。
